config/routes.rb
Rails.application.routes.draw do
  root "invoices#index"

  resources :invoices do
    resources :items
  end
  
  resources :customers
  # get "/invoices", to: "invoices#index"
  # get "/invoices/:id", to: "invoices#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_one :customer
  has_many :items
  
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end
  
  def show
    @invoice = Invoice.find(params[:id])
  end
  
  def new
    @invoice = Invoice.new
  end
  
  def create
    @invoice = Invoice.new(invoice_params)
    
    if @invoice.save
      redirect_to @invoice
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @invoice = Invoice.find(params[:id])
  end
  
  def update
    @invoice = Invoice.find(params[:id])
    
    if @invoice.update(invoice_params)
      redirect_to @invoice
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    
    redirect_to root_path, status: :see_other
  end
  
  private
  def invoice_params
    params.require(:invoice).permit(:title)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @invoice = Invoice.find(params[:invoice_id])
    @item = @invoice.items.create(item_params)
    redirect_to invoice_path(@invoice)
  end
  
  private
  def item_params
    params.require(:item).permit(:title, :description, :price, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/invoices/_form.html.erb
<%= form_with model: invoice do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
        <% invoice.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>

<%= render "form", invoice: @invoice %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<ul>
    <% @invoices.each do |invoice| %>
        <li>
            <%= link_to invoice.title, invoice %>
        </li>
    <% end %>
</ul>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_with model: @invoice do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
        <% @invoice.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/invoices/show.html.erb
<h1><%= @invoice.title %></h1>

<p>This is some text</p>

<ul>
    <li><%= link_to "Edit", edit_invoice_path(@invoice) %></li>
    <li><%= link_to "Destory", invoice_path(@invoice), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
        }%></li>

    <h2>Items</h2>
    <table>
        <tbody>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>

    <% @invoice.items.each do |item| %>
        <tr>
            <td><%= item.title %></td>
            <td><%= item.description %></td>
            <td><%= item.price %></td>
            <td><%= item.quantity %></td>
            <td><%= item.price * item.quantity %></td>
        </tr>
    <% end %>
        </tbody>
    </table>
    
    <h2>Add an Item</h2>
    <%= form_with model: [@invoice, @invoice.items.build] do |form| %>
        <p>
            <%= form.label :title %><br />
            <%= form.text_field :title%>
        </p>
        
        <p>
            <%= form.label :description %><br />
            <%= form.text_area :description %>
        </p>
        
        <p>
            <%= form.label :price %><br />
            <%= form.number_field :price %>
        </p>
        
        <p>
            <%= form.label :quantity %><br />
            <%= form.number_field :quantity%>
        </p>
        
        <p>
            <%= form.submit%>
        </p>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoices</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>